import {
  fromProfileVi,
  type SeedCategory,
  type SeedDocument,
  type SeedSchool,
} from "./types";

/** The four distinct source PDFs. Two of the six files on disk are byte-identical duplicates. */
export const DOCUMENTS: SeedDocument[] = [
  {
    slug: "profile-viet-duc-vi",
    title: {
      vi: "PROFILE VIỆT ĐỨC GROUP (bản tiếng Việt)",
      en: "Viet Duc Group profile (Vietnamese edition)",
      de: "Viet Duc Group Profil (vietnamesische Ausgabe)",
      ja: "Viet Duc Group 会社案内(ベトナム語版)",
      ko: "Viet Duc Group 소개서(베트남어판)",
      "zh-TW": "Viet Duc Group 簡介（越南文版）",
    },
    originalName: "PROFILE VIỆT ĐỨC (1).pdf",
    language: "vi",
    pageCount: 25,
    ocrUsed: true,
    note: "Hồ sơ năng lực chính thức. Trang 4–20 là bản chụp các quyết định thành lập và giấy chứng nhận đăng ký hoạt động giáo dục nghề nghiệp.",
  },
  {
    slug: "profile-viet-duc-en",
    title: {
      vi: "PROFILE VIỆT ĐỨC GROUP (bản tiếng Anh)",
      en: "Viet Duc Group profile (English edition)",
      de: "Viet Duc Group Profil (englische Ausgabe)",
      ja: "Viet Duc Group 会社案内(英語版)",
      ko: "Viet Duc Group 소개서(영문판)",
      "zh-TW": "Viet Duc Group 簡介（英文版）",
    },
    originalName: "PROFILE VIỆT ĐỨC ENGLISH2.pdf.pdf",
    language: "en",
    pageCount: 25,
    ocrUsed: true,
    note: "Bản tiếng Anh của cùng hồ sơ. Các trang giấy phép giữ nguyên tiếng Việt.",
  },
  {
    slug: "nibelc-profile-vi",
    title: {
      vi: "Hồ sơ năng lực NIBELC Group (bản tiếng Việt)",
      en: "NIBELC Group profile (Vietnamese edition)",
      de: "NIBELC Group Profil (vietnamesische Ausgabe)",
      ja: "NIBELC Group 会社案内(ベトナム語版)",
      ko: "NIBELC Group 역량 소개서(베트남어판)",
      "zh-TW": "NIBELC Group 能力簡介（越南文版）",
    },
    originalName: "VI_Hồ sơ Năng lực NIBELC Group.pdf",
    language: "vi",
    pageCount: 46,
    ocrUsed: true,
    note: "Hồ sơ của NIBELC Group – đối tác chiến lược, không phải đơn vị thành viên của Việt Đức Group.",
  },
  {
    slug: "nibelc-profile-en",
    title: {
      vi: "Hồ sơ năng lực NIBELC Group (bản tiếng Anh)",
      en: "NIBELC Group profile (English edition)",
      de: "NIBELC Group Profil (englische Ausgabe)",
      ja: "NIBELC Group 会社案内(英語版)",
      ko: "NIBELC Group 역량 소개서(영문판)",
      "zh-TW": "NIBELC Group 能力簡介（英文版）",
    },
    originalName: "ENG_NIBELC Group Profile.pdf",
    language: "en",
    pageCount: 65,
    ocrUsed: true,
    note: "Hồ sơ của NIBELC Group – đối tác chiến lược.",
  },
];

/**
 * Fields of study. The first six mirror the structure the organisation already
 * used on its previous site; the last three exist because the licences list
 * occupations that do not fit any of those six.
 */
export const CATEGORIES: SeedCategory[] = [
  {
    slug: "ky-thuat-cong-nghiep",
    order: 1,
    name: {
      vi: "Kỹ thuật – Công nghiệp",
      en: "Engineering & industry",
      de: "Technik & Industrie",
      ja: "工学・産業",
      ko: "공학·산업",
      "zh-TW": "工程與工業",
    },
    description: {
      vi: "Ô tô, điện, điện tử, cơ khí, xây dựng và các nghề kỹ thuật gắn với sản xuất.",
      en: "Automotive, electrical, electronics, mechanical engineering, construction and production trades.",
      de: "Fahrzeugtechnik, Elektrotechnik, Elektronik, Maschinenbau, Bau und produktionsnahe Berufe.",
      ja: "自動車、電気、電子、機械、建設、そして生産に結びついた技術職。",
      ko: "자동차, 전기, 전자, 기계, 건설, 그리고 생산 현장의 기술 직종.",
      "zh-TW": "汽車、電機、電子、機械、營建，以及與生產相關的技術職類。",
    },
  },
  {
    slug: "cong-nghe-thong-tin",
    order: 2,
    name: {
      vi: "Công nghệ thông tin",
      en: "Information technology",
      de: "Informationstechnik",
      ja: "情報技術",
      ko: "정보기술",
      "zh-TW": "資訊科技",
    },
    description: {
      vi: "Phát triển phần mềm, quản trị mạng, thiết kế đồ họa và hệ thống thông tin.",
      en: "Software, network administration, graphic design and information systems.",
      de: "Software, Netzwerkadministration, Grafikdesign und Informationssysteme.",
      ja: "ソフトウェア開発、ネットワーク管理、グラフィックデザイン、情報システム。",
      ko: "소프트웨어 개발, 네트워크 관리, 그래픽 디자인, 정보 시스템.",
      "zh-TW": "軟體開發、網路管理、平面設計與資訊系統。",
    },
  },
  {
    slug: "kinh-te-quan-tri",
    order: 3,
    name: {
      vi: "Kinh tế – Quản trị",
      en: "Business & management",
      de: "Wirtschaft & Management",
      ja: "経営・ビジネス",
      ko: "경영·비즈니스",
      "zh-TW": "商業與管理",
    },
    description: {
      vi: "Kinh doanh, kế toán, tài chính, logistics, marketing và quản trị doanh nghiệp.",
      en: "Business, accounting, finance, logistics, marketing and enterprise management.",
      de: "Betriebswirtschaft, Rechnungswesen, Finanzen, Logistik, Marketing und Unternehmensführung.",
      ja: "ビジネス、会計、財務、物流、マーケティング、企業経営。",
      ko: "비즈니스, 회계, 재무, 물류, 마케팅, 기업 경영.",
      "zh-TW": "商業、會計、財務、物流、行銷與企業管理。",
    },
  },
  {
    slug: "du-lich-dich-vu",
    order: 4,
    name: {
      vi: "Du lịch – Dịch vụ",
      en: "Tourism & hospitality",
      de: "Tourismus & Gastgewerbe",
      ja: "観光・ホスピタリティ",
      ko: "관광·서비스",
      "zh-TW": "觀光與服務",
    },
    description: {
      vi: "Lữ hành, khách sạn, nhà hàng, chế biến món ăn và nghiệp vụ dịch vụ.",
      en: "Travel, hotels, restaurants, culinary arts and service operations.",
      de: "Reise, Hotellerie, Gastronomie, Küche und Servicetätigkeiten.",
      ja: "旅行、ホテル、レストラン、調理、そして接客実務。",
      ko: "여행, 호텔, 레스토랑, 조리, 그리고 서비스 실무.",
      "zh-TW": "旅遊、飯店、餐廳、餐飲製備與服務實務。",
    },
  },
  {
    slug: "ngon-ngu",
    order: 5,
    name: {
      vi: "Ngôn ngữ",
      en: "Languages",
      de: "Sprachen",
      ja: "語学",
      ko: "어학",
      "zh-TW": "語言",
    },
    description: {
      vi: "Tiếng Anh, Đức, Hàn, Nhật, Trung và biên – phiên dịch chuyên ngành.",
      en: "English, German, Korean, Japanese, Chinese and specialised interpreting.",
      de: "Englisch, Deutsch, Koreanisch, Japanisch, Chinesisch und Fachdolmetschen.",
      ja: "英語、ドイツ語、韓国語、日本語、中国語、および専門分野の翻訳・通訳。",
      ko: "영어, 독일어, 한국어, 일본어, 중국어, 그리고 전문 분야 번역·통역.",
      "zh-TW": "英語、德語、韓語、日語、華語，以及專業筆譯與口譯。",
    },
  },
  {
    slug: "cham-soc-suc-khoe",
    order: 6,
    name: {
      vi: "Chăm sóc sức khỏe & sắc đẹp",
      en: "Health & beauty care",
      de: "Gesundheit & Schönheitspflege",
      ja: "健康・美容",
      ko: "건강·미용",
      "zh-TW": "健康與美容",
    },
    description: {
      vi: "Chăm sóc sắc đẹp và các nghề chăm sóc con người.",
      en: "Beauty care and personal-care occupations.",
      de: "Schönheitspflege und personennahe Dienstleistungsberufe.",
      ja: "美容と、人を支えるケアの職種。",
      ko: "미용과 사람을 돌보는 직종.",
      "zh-TW": "美容護理與各類照護職業。",
    },
  },
  {
    slug: "su-pham",
    order: 7,
    name: {
      vi: "Sư phạm",
      en: "Teacher training",
      de: "Pädagogik",
      ja: "教員養成",
      ko: "교원 양성",
      "zh-TW": "師資培育",
    },
    description: {
      vi: "Giáo dục mầm non và giáo dục tiểu học trình độ trung cấp.",
      en: "Pre-school and primary teaching at intermediate level.",
      de: "Vorschul- und Grundschulpädagogik auf mittlerer Stufe.",
      ja: "中級課程の幼児教育および初等教育。",
      ko: "중급 과정의 유아교육과 초등교육.",
      "zh-TW": "中級程度的幼兒教育與國小教育。",
    },
  },
  {
    slug: "truyen-thong",
    order: 8,
    name: {
      vi: "Báo chí – Truyền thông",
      en: "Journalism & media",
      de: "Journalismus & Medien",
      ja: "ジャーナリズム・メディア",
      ko: "언론·미디어",
      "zh-TW": "新聞與傳播",
    },
  },
  {
    slug: "luat-hanh-chinh",
    order: 9,
    name: {
      vi: "Luật – Hành chính",
      en: "Law & administration",
      de: "Recht & Verwaltung",
      ja: "法律・行政",
      ko: "법률·행정",
      "zh-TW": "法律與行政",
    },
  },
];

export const SCHOOLS: SeedSchool[] = [
  {
    slug: "cao-dang-cong-nghe-ngoai-thuong",
    order: 1,
    name: {
      vi: "Trường Cao đẳng Công nghệ – Ngoại thương",
      en: "Foreign Trade Technology College",
      de: "Foreign Trade Technology College",
      ja: "貿易技術短期大学",
      ko: "무역기술전문대학",
      "zh-TW": "外貿科技專科學校",
    },
    shortName: {
      vi: "Cao đẳng Công nghệ Ngoại thương",
      en: "Foreign Trade Technology College",
      ja: "貿易技術短期大学",
      ko: "무역기술전문대학",
      "zh-TW": "外貿科技專科學校",
    },
    tagline: {
      vi: "Hội nhập – Sáng tạo – Thành công",
      en: "Integration – Creativity – Success",
      de: "Integration – Kreativität – Erfolg",
      ja: "国際性 — 創造性 — 成功",
      ko: "국제화 — 창의 — 성공",
      "zh-TW": "接軌國際 — 勇於創新 — 邁向成功",
    },
    summary: {
      vi: "Trường Cao đẳng Công nghệ Ngoại thương là cơ sở đào tạo trực thuộc hệ thống Việt Đức Group, với sứ mệnh cung cấp nguồn nhân lực có tay nghề cao; sáng tạo, đột phá tư duy và có thể nghiên cứu ứng dụng trong thực tế, mang đến cơ hội học tập, phát triển con người toàn diện, hướng đến sự thành công. Góp phần phát triển nguồn nhân lực phục vụ sự nghiệp hội nhập quốc tế.",
      en: "Foreign Trade Technology College is a reputable training institution within the Viet Duc Group system. Its mission is to provide highly skilled human resources with innovative, breakthrough thinking and the ability to apply research in practice, offering opportunities for learning and all-round personal development on the way to success, and contributing to the human resources that serve international integration.",
      de: "Das Foreign Trade Technology College gehört zum Verbund der Viet Duc Group. Sein Auftrag ist die Ausbildung hoch qualifizierter Fachkräfte mit innovativem Denken und praktischer Anwendungsfähigkeit – für die persönliche Entwicklung der Lernenden und für Fachkräfte, die die internationale Integration des Landes tragen.",
      ja: "貿易技術短期大学は Viet Duc Group に属する教育機関です。高い技能をもち、創造的で発想の枠を越え、研究を実務に生かせる人材を育てること、学びの機会と全人的な成長を届けて成功へ導くこと、そして国際化を支える人材の育成に寄与することを使命としています。",
      ko: "무역기술전문대학은 Viet Duc Group에 속한 교육 기관입니다. 높은 기능을 갖추고 창의적으로 사고하며 연구를 실무에 적용할 수 있는 인재를 길러 내고, 배움의 기회와 전인적 성장을 제공하여 성공으로 이끌며, 국제화를 뒷받침할 인재 양성에 이바지하는 것을 사명으로 삼습니다.",
      "zh-TW":
        "外貿科技專科學校為 Viet Duc Group 體系內的教育機構，以培育技術精湛、思維創新且能將研究應用於實務的人才為使命，提供學習機會與全人發展，引領學子邁向成功，並為國際化所需的人力培育貢獻力量。",
    },
    legalNameEn: "Foreign Trade & Technology College",
    city: {
      vi: "Đà Nẵng",
      en: "Da Nang",
      de: "Da Nang",
      ja: "ダナン",
      ko: "다낭",
      "zh-TW": "峴港",
    },
    address: "Số 42-44-46 Phan Châu Trinh, phường Hải Châu, thành phố Đà Nẵng",
    phone: "0799 090 988 – 0899 944 101",
    email: "tuyensinh@ngoaithuongcollege.edu.vn",
    website: "https://ngoaithuongcollege.edu.vn",
    coverPath: "/media/schools/cao-dang-cong-nghe-ngoai-thuong.webp",
    logoPath: "/media/schools/logos/cao-dang-cong-nghe-ngoai-thuong.webp",
    highlights: {
      vi: [
        "Đào tạo đa ngành, đa nghề ở hệ cao đẳng, trung cấp và 9+",
        "Chú trọng thực hành, gắn kết doanh nghiệp",
        "Định hướng ứng dụng, hội nhập quốc tế",
      ],
      en: [
        "Multi-disciplinary education at college, intermediate and 9+ levels",
        "Practice-oriented training closely connected with enterprises",
        "Career-focused programmes with international integration",
      ],
      de: [
        "Fächerübergreifende Ausbildung auf College-, Fachschul- und 9+-Niveau",
        "Praxisorientierte Ausbildung in enger Verbindung mit Unternehmen",
        "Berufsbezogene Programme mit internationaler Ausrichtung",
      ],
    },
    legalRefs: [
      {
        label: {
          vi: "Quyết định thành lập Trường Cao đẳng Lạc Việt",
          en: "Decision establishing Lac Viet College",
          ja: "ラクヴィエット短期大学の設立決定",
          ko: "락비엣 전문대학 설립 결정",
          "zh-TW": "設立雒越專科學校之決定",
        },
        number: "5996/QĐ-BGDĐT",
        date: "2008-09-10",
        issuer: {
          vi: "Bộ Giáo dục và Đào tạo",
          en: "Ministry of Education and Training",
          ja: "教育訓練省",
          ko: "교육훈련부",
          "zh-TW": "教育與培訓部",
        },
      },
      {
        label: {
          vi: "Quyết định đổi tên thành Trường Cao đẳng Công nghệ – Ngoại thương",
          en: "Decision renaming to Foreign Trade Technology College",
          ja: "貿易技術短期大学への改称決定",
          ko: "무역기술전문대학으로의 교명 변경 결정",
          "zh-TW": "更名為外貿科技專科學校之決定",
        },
        number: "1279/QĐ-LĐTBXH",
        date: "2023-08-30",
        issuer: {
          vi: "Bộ Lao động – Thương binh và Xã hội",
          en: "Ministry of Labour, Invalids and Social Affairs",
          ja: "労働・傷病兵・社会省",
          ko: "노동보훈사회부",
          "zh-TW": "勞動、榮軍與社會部",
        },
      },
      {
        label: {
          vi: "Giấy chứng nhận đăng ký hoạt động giáo dục nghề nghiệp",
          en: "Certificate of vocational education activity registration",
          ja: "技能教育活動の立案証明書",
          ko: "직업교육 활동 인가증",
          "zh-TW": "技職教育活動立案證明書",
        },
        number: "69/2023/GCNĐKHĐ-TCGDNN",
        date: "2023-09-14",
        issuer: {
          vi: "Tổng cục Giáo dục nghề nghiệp",
          en: "Directorate of Vocational Education and Training",
          ja: "職業教育訓練総局",
          ko: "직업교육훈련총국",
          "zh-TW": "技職教育總局",
        },
      },
    ],
    stats: [
      {
        value: "15+",
        label: {
          vi: "năm hình thành và phát triển",
          en: "years of formation and development",
          de: "Jahre Aufbau und Entwicklung",
          ja: "年の歩み",
          ko: "년의 발자취",
          "zh-TW": "年的發展歷程",
        },
      },
      {
        value: "5.000+",
        label: {
          vi: "học sinh, sinh viên đang theo học",
          en: "students enrolled",
          de: "eingeschriebene Lernende",
          ja: "人の在学生",
          ko: "명의 재학생",
          "zh-TW": "位在學學生",
        },
      },
      {
        value: "200+",
        label: {
          vi: "doanh nghiệp đối tác",
          en: "partner enterprises",
          de: "Partnerunternehmen",
          ja: "の提携企業",
          ko: "개 협력 기업",
          "zh-TW": "家合作企業",
        },
      },
      {
        value: "98%",
        label: {
          vi: "sinh viên có việc làm sau tốt nghiệp",
          en: "graduates employed after graduation",
          de: "Absolventen in Beschäftigung",
          ja: "の卒業生が就職",
          ko: "의 졸업생이 취업",
          "zh-TW": "的畢業生順利就業",
        },
      },
    ],
    provenance: fromProfileVi(4),
    editorNote:
      "Trang thiết kế (tr.4) nêu ngành 'Cử nhân Điều dưỡng' và 'Cao đẳng Điều dưỡng' nhưng giấy chứng nhận 69/2023 KHÔNG có mã ngành điều dưỡng. Chưa đưa hai ngành này lên website – cần trường cung cấp giấy phép bổ sung. Địa chỉ cập nhật 08/09/2026 theo Việt Đức Group cung cấp: 'quận Hải Châu' đổi thành 'phường Hải Châu' sau sáp nhập đơn vị hành chính.",
  },
  {
    slug: "trung-cap-nghe-quoc-te-ivs",
    order: 2,
    name: {
      vi: "Trường Trung cấp nghề Quốc tế (IVS)",
      en: "International Vocational School (IVS)",
      de: "International Vocational School (IVS)",
      ja: "国際職業訓練学校(IVS)",
      ko: "국제직업학교(IVS)",
      "zh-TW": "國際職業學校（IVS）",
    },
    shortName: {
      vi: "Trung cấp nghề Quốc tế (IVS)",
      en: "IVS",
      ja: "IVS 国際職業校",
      ko: "IVS 국제직업학교",
      "zh-TW": "IVS 國際職業學校",
    },
    tagline: {
      vi: "Đào tạo chuẩn quốc tế – Cơ hội toàn cầu",
      en: "International standard education – a solid foundation for a global future",
      de: "Ausbildung nach internationalem Standard – Grundlage für eine globale Zukunft",
      ja: "国際水準の教育 — 世界へ開かれた機会",
      ko: "국제 수준의 교육 — 세계로 열린 기회",
      "zh-TW": "國際標準的培訓 — 通向全球的機會",
    },
    summary: {
      vi: "Trung cấp nghề Quốc tế (IVS) là đơn vị thành viên của Việt Đức Group, cung cấp chương trình đào tạo đạt chuẩn quốc tế, liên kết với các đối tác uy tín trong và ngoài nước. IVS định hướng đào tạo nguồn nhân lực chất lượng cao, thành thạo kỹ năng nghề nghiệp, ngoại ngữ và tác phong công nghiệp, sẵn sàng làm việc tại Việt Nam và trên thế giới.",
      en: "IVS is a member of Viet Duc Group, offering international standard education programmes closely aligned with reputable global institutions. IVS aims to train high-quality human resources, develop professional skills, enhance creative thinking, meet the needs of businesses, and brighten career opportunities for Vietnamese youth in the era of globalisation.",
      de: "Die IVS gehört zur Viet Duc Group und bietet Programme nach internationalem Standard in Zusammenarbeit mit renommierten Partnern im In- und Ausland. Ziel ist die Ausbildung qualifizierter Fachkräfte mit beruflichen Fertigkeiten, Fremdsprachenkenntnissen und industrietauglicher Arbeitshaltung – für den Einsatz in Vietnam und weltweit.",
      ja: "国際職業訓練学校(IVS)は Viet Duc Group の加盟校で、国内外の信頼できる提携先と結んだ国際水準の教育課程を提供しています。職業技能・外国語・産業現場の作法を身につけた質の高い人材を育て、ベトナム国内でも海外でも働ける力を養うことを目指しています。",
      ko: "국제직업학교(IVS)는 Viet Duc Group의 회원 학교로, 국내외 신뢰할 만한 협력 기관과 함께 국제 수준의 교육 과정을 제공합니다. 직업 기능과 외국어, 산업 현장의 태도를 두루 갖춘 수준 높은 인재를 길러 베트남과 해외 어디서든 일할 수 있도록 준비시킵니다.",
      "zh-TW":
        "國際職業學校（IVS）為 Viet Duc Group 的成員學校，提供符合國際標準的課程，並與國內外具公信力的夥伴合作。IVS 致力培育兼具職業技能、外語能力與產業工作態度的優質人才，使其能在越南及世界各地就業。",
    },
    legalNameEn: "International Vocational School (IVS)",
    city: {
      vi: "Ninh Bình",
      en: "Ninh Binh",
      de: "Ninh Binh",
      ja: "ニンビン",
      ko: "닌빈",
      "zh-TW": "寧平",
    },
    address: "Km 10, Quốc lộ 1A, xã Gia Trấn, tỉnh Ninh Bình",
    phone: "0229 3868 231",
    email: "tcqtivs@gmail.com",
    website: "https://ivs.edu.vn",
    coverPath: "/media/schools/trung-cap-nghe-quoc-te-ivs.webp",
    logoPath: "/media/schools/logos/trung-cap-nghe-quoc-te-ivs.webp",
    highlights: {
      vi: [
        "Đào tạo đa ngành, đa nghề ở hệ trung cấp và 9+",
        "Chương trình đào tạo chuẩn quốc tế",
        "Liên kết với đối tác nước ngoài, cơ hội học tập và làm việc toàn cầu",
        "Phát triển kỹ năng và năng lực công dân toàn cầu",
      ],
      en: [
        "Multi-disciplinary vocational education at intermediate and 9+ levels",
        "International-standard training programmes",
        "Partnerships with overseas institutions, creating global study and employment opportunities",
        "Developing professional competence and globally competitive skills",
      ],
      de: [
        "Fächerübergreifende Berufsausbildung auf Fachschul- und 9+-Niveau",
        "Programme nach internationalem Standard",
        "Partnerschaften mit Einrichtungen im Ausland für Studium und Beschäftigung",
        "Entwicklung beruflicher und global wettbewerbsfähiger Kompetenzen",
      ],
    },
    legalRefs: [
      {
        label: {
          vi: "Quyết định cho phép thành lập Trường Trung cấp nghề Quốc tế",
          en: "Decision permitting establishment of IVS",
          ja: "国際職業訓練学校の設立認可決定",
          ko: "국제직업학교 설립 허가 결정",
          "zh-TW": "核准設立國際職業學校之決定",
        },
        number: "470/QĐ-UBND",
        date: "2016-09-15",
        issuer: {
          vi: "UBND tỉnh Ninh Bình",
          en: "Ninh Binh Provincial People's Committee",
          ja: "ニンビン省人民委員会",
          ko: "닌빈성 인민위원회",
          "zh-TW": "寧平省人民委員會",
        },
      },
      {
        label: {
          vi: "Giấy chứng nhận đăng ký hoạt động giáo dục nghề nghiệp",
          en: "Certificate of vocational education activity registration",
          ja: "技能教育活動の立案証明書",
          ko: "직업교육 활동 인가증",
          "zh-TW": "技職教育活動立案證明書",
        },
        number: "01/GCNĐKHĐ-LĐTBXH",
        date: "2017-02-06",
        issuer: {
          vi: "Sở Lao động – Thương binh và Xã hội tỉnh Ninh Bình",
          en: "Ninh Binh Department of Labour, Invalids and Social Affairs",
          ja: "ニンビン省労働・傷病兵・社会局",
          ko: "닌빈성 노동보훈사회국",
          "zh-TW": "寧平省勞動榮軍與社會廳",
        },
      },
      {
        label: {
          vi: "Giấy chứng nhận đăng ký bổ sung hoạt động giáo dục nghề nghiệp",
          en: "Supplementary registration certificate",
          ja: "技能教育活動の追加立案証明書",
          ko: "직업교육 활동 추가 인가증",
          "zh-TW": "技職教育活動增列立案證明書",
        },
        number: "01/GCNĐKBS-LĐTBXH",
        date: "2017-04-14",
        issuer: {
          vi: "Sở Lao động – Thương binh và Xã hội tỉnh Ninh Bình",
          en: "Ninh Binh Department of Labour, Invalids and Social Affairs",
          ja: "ニンビン省労働・傷病兵・社会局",
          ko: "닌빈성 노동보훈사회국",
          "zh-TW": "寧平省勞動榮軍與社會廳",
        },
      },
      {
        label: {
          vi: "Giấy chứng nhận đăng ký bổ sung hoạt động giáo dục nghề nghiệp",
          en: "Supplementary registration certificate",
          ja: "技能教育活動の追加立案証明書",
          ko: "직업교육 활동 추가 인가증",
          "zh-TW": "技職教育活動增列立案證明書",
        },
        number: "04/GCNĐKBSHĐ-LĐTBXH",
        date: "2018-01-19",
        issuer: {
          vi: "Sở Lao động – Thương binh và Xã hội tỉnh Ninh Bình",
          en: "Ninh Binh Department of Labour, Invalids and Social Affairs",
          ja: "ニンビン省労働・傷病兵・社会局",
          ko: "닌빈성 노동보훈사회국",
          "zh-TW": "寧平省勞動榮軍與社會廳",
        },
      },
      {
        label: {
          vi: "Giấy chứng nhận đăng ký bổ sung hoạt động giáo dục nghề nghiệp",
          en: "Supplementary registration certificate",
          ja: "技能教育活動の追加立案証明書",
          ko: "직업교육 활동 추가 인가증",
          "zh-TW": "技職教育活動增列立案證明書",
        },
        number: "05/GCNĐKBSHĐ-LĐTBXH",
        date: "2018-05-30",
        issuer: {
          vi: "Sở Lao động – Thương binh và Xã hội tỉnh Ninh Bình",
          en: "Ninh Binh Department of Labour, Invalids and Social Affairs",
          ja: "ニンビン省労働・傷病兵・社会局",
          ko: "닌빈성 노동보훈사회국",
          "zh-TW": "寧平省勞動榮軍與社會廳",
        },
      },
    ],
    stats: [
      {
        value: "10+",
        label: {
          vi: "năm hình thành và phát triển",
          en: "years of experience and development",
          de: "Jahre Erfahrung und Entwicklung",
          ja: "年の歩み",
          ko: "년의 발자취",
          "zh-TW": "年的發展歷程",
        },
      },
      {
        value: "12+",
        label: {
          vi: "ngành nghề đào tạo",
          en: "training majors",
          de: "Ausbildungsrichtungen",
          ja: "の教育課程",
          ko: "개 교육 과정",
          "zh-TW": "個培訓課程",
        },
      },
      {
        value: "95%",
        label: {
          vi: "sinh viên có việc làm sau tốt nghiệp",
          en: "students employed after graduation",
          de: "Absolventen in Beschäftigung",
          ja: "の卒業生が就職",
          ko: "의 졸업생이 취업",
          "zh-TW": "的畢業生順利就業",
        },
      },
      {
        value: "50+",
        label: {
          vi: "đối tác quốc tế uy tín",
          en: "international partners",
          de: "internationale Partner",
          ja: "の信頼できる海外提携先",
          ko: "곳의 믿을 만한 해외 협력사",
          "zh-TW": "個具公信力的國際夥伴",
        },
      },
    ],
    provenance: fromProfileVi(6),
    editorNote:
      "Các giấy chứng nhận 2017–2018 ghi 'có hiệu lực 05 năm kể từ ngày ký' – cần trường cung cấp giấy chứng nhận gia hạn/cấp lại còn hiệu lực trước khi công bố chỉ tiêu tuyển sinh. Địa chỉ cập nhật 08/09/2026 theo Việt Đức Group cung cấp: bỏ cấp huyện ('huyện Gia Viễn') sau sáp nhập đơn vị hành chính, xã Gia Trấn nay trực thuộc tỉnh Ninh Bình.",
  },
  {
    slug: "trung-cap-bach-khoa-vung-tau",
    order: 3,
    name: {
      vi: "Trường Trung cấp Bách khoa Vũng Tàu",
      en: "Bach Khoa Vung Tau Vocational School",
      de: "Bach Khoa Vung Tau Berufsfachschule",
      ja: "ブンタウ工科中級学校",
      ko: "붕따우 공과중급학교",
      "zh-TW": "頭頓百科中級學校",
    },
    shortName: {
      vi: "Trung cấp Bách khoa Vũng Tàu",
      en: "Bach Khoa Vung Tau",
      ja: "ブンタウ工科校",
      ko: "붕따우 공과학교",
      "zh-TW": "頭頓百科",
    },
    tagline: {
      vi: "Kỹ thuật vững vàng – Nghề nghiệp tương lai",
      en: "Solid technical skills – shaping the future",
      de: "Solide Technik – Beruf mit Zukunft",
      ja: "確かな技術 — これからの職業へ",
      ko: "탄탄한 기술 — 앞날의 직업으로",
      "zh-TW": "紮實的技術 — 通往未來的職業",
    },
    summary: {
      vi: "Trung cấp Bách khoa Vũng Tàu là đơn vị thành viên của Việt Đức Group, chuyên đào tạo nhóm ngành kỹ thuật – công nghệ. Nhà trường chú trọng thực hành, trang bị kiến thức và kỹ năng chuyên môn vững chắc, đáp ứng nhu cầu của doanh nghiệp và thị trường lao động.",
      en: "Bach Khoa Vung Tau is a member of Viet Duc Group specialising in technical and technological fields. The school focuses on practical training, modern facilities and professional subjects, building the skills that businesses and the labour market need.",
      de: "Die Bach Khoa Vung Tau gehört zur Viet Duc Group und ist auf technische und technologische Fachrichtungen spezialisiert. Im Mittelpunkt stehen praktische Ausbildung, moderne Werkstätten und fachliche Tiefe entsprechend dem Bedarf der Unternehmen.",
      ja: "ブンタウ工科中級学校は Viet Duc Group の加盟校で、工学・技術系の分野を専門としています。実習を重んじ、確かな専門知識と技能を身につけさせて、企業と労働市場の求めに応えます。",
      ko: "붕따우 공과중급학교는 Viet Duc Group의 회원 학교로 공학·기술 분야를 전문으로 합니다. 실습을 중시하여 탄탄한 전문 지식과 기능을 갖추게 하고, 기업과 노동시장의 요구에 부응합니다.",
      "zh-TW":
        "頭頓百科中級學校為 Viet Duc Group 的成員學校，專攻工程與技術領域。學校重視實作，培養紮實的專業知識與技能，以因應企業與勞動市場的需求。",
    },
    legalNameEn: "Vung Tau College of Technology",
    city: {
      vi: "TP. Hồ Chí Minh",
      en: "Ho Chi Minh City",
      de: "Ho-Chi-Minh-Stadt",
      ja: "ホーチミン市",
      ko: "호찌민시",
      "zh-TW": "胡志明市",
    },
    address: "Số 565 Trương Công Định, phường Tam Thắng, Thành phố Hồ Chí Minh",
    website: "https://bachkhoavungtau.edu.vn",
    email: "trungcapbachkhoavt2023@gmail.com",
    phone: "0911 762 666",
    coverPath: "/media/schools/trung-cap-bach-khoa-vung-tau.webp",
    logoPath: "/media/schools/logos/trung-cap-bach-khoa-vung-tau.webp",
    highlights: {
      vi: [
        "Đào tạo đa ngành, đa nghề ở hệ trung cấp và 9+",
        "Đào tạo các ngành kỹ thuật, công nghệ, cơ khí, điện – điện tử, công nghệ thông tin",
        "Thực hành chuyên sâu, đáp ứng nhu cầu doanh nghiệp",
        "Nền tảng vững chắc cho sự nghiệp bền vững",
      ],
      en: [
        "Multi-disciplinary vocational education at intermediate and 9+ levels",
        "Technical training in mechanical engineering, electrical, electronics, automotive and information technology",
        "Intensive practical training aligned with industry demands",
        "A strong foundation for sustainable career development",
      ],
      de: [
        "Fächerübergreifende Berufsausbildung auf Fachschul- und 9+-Niveau",
        "Technische Ausbildung in Maschinenbau, Elektro-, Elektronik-, Fahrzeug- und Informationstechnik",
        "Intensive Praxisausbildung entlang der Anforderungen der Industrie",
        "Solide Grundlage für eine nachhaltige Berufslaufbahn",
      ],
    },
    legalRefs: [
      {
        label: {
          vi: "Quyết định cho phép thành lập Trường Trung cấp Công nghệ thông tin TM.COMPUTER",
          en: "Decision establishing TM.COMPUTER Information Technology Vocational School",
          ja: "TM.COMPUTER 情報技術中級学校の設立認可決定",
          ko: "TM.COMPUTER 정보기술중급학교 설립 허가 결정",
          "zh-TW": "核准設立 TM.COMPUTER 資訊科技中級學校之決定",
        },
        number: "3181/QĐ-UBND",
        date: "2006-10-09",
        issuer: {
          vi: "UBND tỉnh Bà Rịa – Vũng Tàu",
          en: "Ba Ria – Vung Tau Provincial People's Committee",
          ja: "バリア・ブンタウ省人民委員会",
          ko: "바리아붕따우성 인민위원회",
          "zh-TW": "巴地頭頓省人民委員會",
        },
      },
      {
        label: {
          vi: "Quyết định đổi tên trường",
          en: "Decision renaming the school",
          ja: "校名変更の決定",
          ko: "교명 변경 결정",
          "zh-TW": "校名變更之決定",
        },
        number: "1461/QĐ-UBND",
        date: "2013-07-25",
        issuer: {
          vi: "UBND tỉnh Bà Rịa – Vũng Tàu",
          en: "Ba Ria – Vung Tau Provincial People's Committee",
          ja: "バリア・ブンタウ省人民委員会",
          ko: "바리아붕따우성 인민위원회",
          "zh-TW": "巴地頭頓省人民委員會",
        },
      },
      {
        label: {
          vi: "Quyết định đổi tên thành Trường Trung cấp Bách khoa Vũng Tàu",
          en: "Decision renaming to Bach Khoa Vung Tau Vocational School",
          ja: "ブンタウ工科中級学校への改称決定",
          ko: "붕따우 공과중급학교로의 교명 변경 결정",
          "zh-TW": "更名為頭頓百科中級學校之決定",
        },
        number: "3802/QĐ-UBND",
        date: "2017-12-29",
        issuer: {
          vi: "UBND tỉnh Bà Rịa – Vũng Tàu",
          en: "Ba Ria – Vung Tau Provincial People's Committee",
          ja: "バリア・ブンタウ省人民委員会",
          ko: "바리아붕따우성 인민위원회",
          "zh-TW": "巴地頭頓省人民委員會",
        },
      },
      {
        label: {
          vi: "Giấy chứng nhận đăng ký hoạt động giáo dục nghề nghiệp",
          en: "Certificate of vocational education activity registration",
          ja: "技能教育活動の立案証明書",
          ko: "직업교육 활동 인가증",
          "zh-TW": "技職教育活動立案證明書",
        },
        number: "71/GCNĐKHĐ-SLĐTBXH",
        date: "2021-05-26",
        issuer: {
          vi: "Sở Lao động – Thương binh và Xã hội tỉnh Bà Rịa – Vũng Tàu",
          en: "Ba Ria – Vung Tau Department of Labour, Invalids and Social Affairs",
          ja: "バリア・ブンタウ省労働・傷病兵・社会局",
          ko: "바리아붕따우성 노동보훈사회국",
          "zh-TW": "巴地頭頓省勞動榮軍與社會廳",
        },
      },
    ],
    stats: [
      {
        value: "15+",
        label: {
          vi: "năm hình thành và phát triển",
          en: "years of formation and development",
          de: "Jahre Aufbau und Entwicklung",
          ja: "年の歩み",
          ko: "년의 발자취",
          "zh-TW": "年的發展歷程",
        },
      },
      {
        value: "10+",
        label: {
          vi: "ngành nghề đào tạo",
          en: "training majors",
          de: "Ausbildungsrichtungen",
          ja: "の教育課程",
          ko: "개 교육 과정",
          "zh-TW": "個培訓課程",
        },
      },
      {
        value: "98%",
        label: {
          vi: "sinh viên có việc làm sau tốt nghiệp",
          en: "students employed after graduation",
          de: "Absolventen in Beschäftigung",
          ja: "の卒業生が就職",
          ko: "의 졸업생이 취업",
          "zh-TW": "的畢業生順利就業",
        },
      },
      {
        value: "200+",
        label: {
          vi: "doanh nghiệp đối tác",
          en: "partner enterprises",
          de: "Partnerunternehmen",
          ja: "の提携企業",
          ko: "개 협력 기업",
          "zh-TW": "家合作企業",
        },
      },
    ],
    provenance: fromProfileVi(7),
    editorNote:
      "Địa chỉ cập nhật ngày 08/09/2026 theo Việt Đức Group cung cấp: 'Số 565 Trương Công Định, phường Tam Thắng, Thành phố Hồ Chí Minh'. Bà Rịa – Vũng Tàu đã sáp nhập vào TP. Hồ Chí Minh, nên tên tỉnh cũ trong giấy chứng nhận 71/GCNĐKHĐ-SLĐTBXH ('phường 7, thành phố Vũng Tàu, tỉnh Bà Rịa – Vũng Tàu') không còn dùng được. Trang thiết kế trong hồ sơ ghi 'TP HCM' — hoá ra khớp với địa giới mới, chỉ thiếu tên phường.",
  },
  {
    slug: "trung-cap-viet-han",
    order: 4,
    name: {
      vi: "Trường Trung cấp Việt Hàn",
      en: "Viet Han Vocational School",
      de: "Viet Han Berufsfachschule",
      ja: "越韓中級学校",
      ko: "베트남·한국 중급학교",
      "zh-TW": "越韓中級學校",
    },
    shortName: {
      vi: "Trung cấp Việt Hàn",
      en: "Viet Han",
      ja: "越韓校",
      ko: "베트남·한국 학교",
      "zh-TW": "越韓",
    },
    tagline: {
      vi: "Công nghệ hiện đại – Hội nhập quốc tế",
      en: "Modern technology – international integration",
      de: "Moderne Technik – internationale Integration",
      ja: "先進の技術 — 世界とつながる",
      ko: "앞선 기술 — 국제 사회와 함께",
      "zh-TW": "先進技術 — 接軌國際",
    },
    summary: {
      vi: "Trung cấp Việt Hàn là đơn vị thành viên của Việt Đức Group, định hướng đào tạo nguồn nhân lực chất lượng cao theo mô hình hợp tác Việt Nam – Hàn Quốc. Nhà trường chú trọng đào tạo kỹ năng nghề nghiệp, ngoại ngữ, tác phong công nghiệp và khả năng hội nhập quốc tế.",
      en: "Viet Han Vocational School is a member institution of Viet Duc Group, oriented toward training high-quality human resources under the Vietnam–Korea cooperation model. The school focuses on vocational skills, foreign languages, industrial working style and international integration.",
      de: "Die Viet Han Berufsfachschule gehört zur Viet Duc Group und bildet Fachkräfte nach dem vietnamesisch-koreanischen Kooperationsmodell aus. Schwerpunkte sind berufliche Fertigkeiten, Fremdsprachen, industrielle Arbeitshaltung und internationale Anschlussfähigkeit.",
      ja: "越韓中級学校は Viet Duc Group の加盟校で、ベトナム・韓国の協力モデルにもとづき質の高い人材を育てています。職業技能、外国語、産業現場の作法、そして国際的に働く力の育成を重んじています。",
      ko: "베트남·한국 중급학교는 Viet Duc Group의 회원 학교로, 베트남·한국 협력 모형에 따라 수준 높은 인재를 길러 냅니다. 직업 기능과 외국어, 산업 현장의 태도, 그리고 국제 사회에서 일할 역량을 중시합니다.",
      "zh-TW":
        "越韓中級學校為 Viet Duc Group 的成員學校，依越南與韓國的合作模式培育優質人才。學校著重職業技能、外語、產業工作態度，以及與國際接軌的能力。",
    },
    city: {
      vi: "Đồng Nai",
      en: "Dong Nai",
      de: "Dong Nai",
      ja: "ドンナイ省",
      ko: "동나이성",
      "zh-TW": "同奈省",
    },
    address: "Khu phố Thanh Bình, phường Bình Phước, tỉnh Đồng Nai, Việt Nam",
    email: "trungcapviethan.vki@gmail.com",
    phone: "0911 762 666",
    coverPath: "/media/schools/trung-cap-viet-han.webp",
    logoPath: "/media/schools/logos/trung-cap-viet-han.webp",
    highlights: {
      vi: [
        "Đào tạo đa ngành, đa nghề ở hệ trung cấp và 9+",
        "Đào tạo theo mô hình hợp tác Việt Nam – Hàn Quốc",
        "Ngôn ngữ, kỹ năng và tác phong chuẩn Hàn Quốc",
        "Cơ hội việc làm tại các doanh nghiệp Hàn Quốc trong và ngoài nước",
      ],
      en: [
        "Multi-disciplinary vocational education at intermediate and 9+ levels",
        "Vietnam–South Korea collaborative training programmes",
        "Korean language training and Korean-standard vocational skills",
        "Employment opportunities with Korean enterprises both in Vietnam and abroad",
      ],
      de: [
        "Fächerübergreifende Berufsausbildung auf Fachschul- und 9+-Niveau",
        "Ausbildungsprogramme in vietnamesisch-koreanischer Kooperation",
        "Koreanischunterricht und Fertigkeiten nach koreanischem Standard",
        "Beschäftigungsmöglichkeiten bei koreanischen Unternehmen im In- und Ausland",
      ],
    },
    legalRefs: [
      {
        label: {
          vi: "Quyết định thành lập Trường Trung học Dân lập Kinh tế – Kỹ thuật Bình Phước",
          en: "Decision establishing Binh Phuoc Economics – Technology People-founded Secondary School",
          ja: "ビンフオック私立経済技術中等学校の設立決定",
          ko: "빈프억 사립 경제기술 중등학교 설립 결정",
          "zh-TW": "設立平福民辦經濟技術中學之決定",
        },
        number: "09/2004/QĐ-UB",
        date: "2004-02-03",
        issuer: {
          vi: "UBND tỉnh Bình Phước",
          en: "Binh Phuoc Provincial People's Committee",
          ja: "ビンフオック省人民委員会",
          ko: "빈프억성 인민위원회",
          "zh-TW": "平福省人民委員會",
        },
      },
      {
        label: {
          vi: "Quyết định cho phép hoạt động giáo dục nghề nghiệp đào tạo giáo viên mầm non, tiểu học trình độ trung cấp",
          en: "Decision permitting intermediate-level pre-school and primary teacher training",
          ja: "中級課程における幼稚園・小学校教員養成の技能教育活動を認可する決定",
          ko: "중급 과정의 유치원·초등학교 교원 양성 직업교육 활동 허가 결정",
          "zh-TW": "核准辦理中級程度幼兒園與國小師資培育技職教育活動之決定",
        },
        number: "561/QĐ-SGDĐT",
        date: "2019-03-07",
        issuer: {
          vi: "Sở Giáo dục và Đào tạo tỉnh Bình Phước",
          en: "Binh Phuoc Department of Education and Training",
          ja: "ビンフオック省教育訓練局",
          ko: "빈프억성 교육훈련국",
          "zh-TW": "平福省教育與培訓廳",
        },
      },
      {
        label: {
          vi: "Quyết định đổi tên Trường Trung cấp Kinh tế – Kỹ thuật Bình Phước thành Trường Trung cấp Việt Hàn",
          en: "Decision renaming to Viet Han Vocational School",
          ja: "ビンフオック経済技術中級学校を越韓中級学校へ改称する決定",
          ko: "빈프억 경제기술중급학교를 베트남·한국 중급학교로 변경하는 결정",
          "zh-TW": "將平福經濟技術中級學校更名為越韓中級學校之決定",
        },
        number: "1219/QĐ-UBND",
        date: "2020-06-04",
        issuer: {
          vi: "UBND tỉnh Bình Phước",
          en: "Binh Phuoc Provincial People's Committee",
          ja: "ビンフオック省人民委員会",
          ko: "빈프억성 인민위원회",
          "zh-TW": "平福省人民委員會",
        },
      },
    ],
    stats: [
      {
        value: "12+",
        label: {
          vi: "ngành nghề đào tạo",
          en: "training majors",
          de: "Ausbildungsrichtungen",
          ja: "の教育課程",
          ko: "개 교육 과정",
          "zh-TW": "個培訓課程",
        },
      },
      {
        value: "95%",
        label: {
          vi: "sinh viên có việc làm sau tốt nghiệp",
          en: "students employed after graduation",
          de: "Absolventen in Beschäftigung",
          ja: "の卒業生が就職",
          ko: "의 졸업생이 취업",
          "zh-TW": "的畢業生順利就業",
        },
      },
      {
        value: "100+",
        label: {
          vi: "doanh nghiệp đối tác",
          en: "partner enterprises",
          de: "Partnerunternehmen",
          ja: "の提携企業",
          ko: "개 협력 기업",
          "zh-TW": "家合作企業",
        },
      },
    ],
    provenance: fromProfileVi(18),
    editorNote:
      "Hồ sơ in gọi trường là 'Trung cấp Việt Hàn Đồng Nai'; các quyết định gốc ghi địa chỉ tại Bình Phước (nay thuộc tỉnh Đồng Nai sau sáp nhập 2025). Đã dùng tên pháp lý 'Trường Trung cấp Việt Hàn' theo QĐ 1219/QĐ-UBND. Ngoài hai mã ngành sư phạm, hồ sơ chưa kèm giấy chứng nhận đăng ký hoạt động GDNN liệt kê mã ngành nghề khác – các ngành còn lại đang để ở dạng định hướng đào tạo, chưa công bố chỉ tiêu. Địa chỉ cập nhật 08/09/2026 theo Việt Đức Group cung cấp: 'Khu phố Thanh Bình, phường Bình Phước, tỉnh Đồng Nai' — tên phường cũ 'Tân Bình' và cấp 'thành phố Đồng Xoài' không còn dùng.",
  },
  {
    slug: "trung-cap-cong-nghe-viet-duc",
    order: 5,
    name: {
      vi: "Trường Trung cấp Công nghệ Việt Đức",
      en: "Viet Duc Vocational School of Technology",
      de: "Viet Duc Berufsfachschule für Technik",
      ja: "越独技術中級学校",
      ko: "베트남·독일 기술중급학교",
      "zh-TW": "越德科技中級學校",
    },
    shortName: {
      vi: "Trung cấp Công nghệ Việt Đức",
      en: "Viet Duc College of Technology",
      ja: "越独技術校",
      ko: "베트남·독일 기술학교",
      "zh-TW": "越德科技",
    },
    tagline: {
      vi: "Đào tạo thực chất – Kỹ năng vững chắc – Việc làm bền vững – Tương lai rộng mở",
      en: "Practical training – solid skills – bright futures",
      de: "Praxisnahe Ausbildung – solide Fertigkeiten – offene Zukunft",
      ja: "中身のある教育 — 確かな技能 — 続く仕事 — 開けた未来",
      ko: "내실 있는 교육 — 탄탄한 기능 — 오래가는 일자리 — 열린 미래",
      "zh-TW": "扎實的教學 — 穩固的技能 — 長久的工作 — 開闊的未來",
    },
    summary: {
      vi: "Trung cấp Công nghệ Việt Đức là đơn vị thành viên của Việt Đức Group, đào tạo đa ngành, đa nghề ở hệ trung cấp. Nhà trường chú trọng thực hành, trang bị kỹ năng nghề nghiệp vững vàng, đáp ứng nhu cầu của doanh nghiệp và thị trường lao động.",
      en: "Viet Duc College of Technology is a member school of Viet Duc Group, offering multi-disciplinary education at intermediate level. The school focuses on hands-on training, equipping students with solid professional skills to meet the needs of businesses and the labour market.",
      de: "Die Viet Duc Berufsfachschule für Technik gehört zur Viet Duc Group und bildet fächerübergreifend auf Fachschulniveau aus. Der Schwerpunkt liegt auf praktischer Ausbildung und soliden beruflichen Fertigkeiten entsprechend dem Bedarf der Unternehmen.",
      ja: "越独技術中級学校は Viet Duc Group の加盟校で、中級課程において幅広い分野・職種の教育を行っています。実習を重んじ、確かな職業技能を身につけさせて、企業と労働市場の求めに応えます。",
      ko: "베트남·독일 기술중급학교는 Viet Duc Group의 회원 학교로, 중급 과정에서 여러 분야와 직종을 아우르는 교육을 합니다. 실습을 중시하여 탄탄한 직업 기능을 갖추게 하고, 기업과 노동시장의 요구에 부응합니다.",
      "zh-TW":
        "越德科技中級學校為 Viet Duc Group 的成員學校，於中級學制開設多元領域與職類的課程。學校重視實作，培養紮實的職業技能，以因應企業與勞動市場的需求。",
    },
    city: {
      vi: "Quảng Trị",
      en: "Quang Tri",
      de: "Quang Tri",
      ja: "クアンチ",
      ko: "꽝찌",
      "zh-TW": "廣治",
    },
    address: "Tổ dân phố 15, phường Đồng Thuận, tỉnh Quảng Trị",
    phone: "0911 762 666",
    coverPath: "/media/schools/trung-cap-cong-nghe-viet-duc.webp",
    logoPath: "/media/schools/logos/trung-cap-cong-nghe-viet-duc.webp",
    highlights: {
      vi: [
        "Đào tạo đa ngành, đa nghề ở hệ trung cấp và 9+",
        "Trang thiết bị hiện đại, đội ngũ giảng viên giàu kinh nghiệm",
        "Chú trọng thực hành – 70% thời lượng",
      ],
      en: [
        "Multi-disciplinary education at intermediate and 9+ levels",
        "Modern facilities and highly experienced faculty",
        "Practice-first curriculum – 70% hands-on",
      ],
      de: [
        "Fächerübergreifende Ausbildung auf Fachschul- und 9+-Niveau",
        "Moderne Ausstattung und erfahrenes Lehrpersonal",
        "Praxis zuerst – 70 % der Ausbildungszeit",
      ],
    },
    legalRefs: [
      {
        label: {
          vi: "Quyết định cho phép thành lập Trường Trung cấp Công nghệ Việt Đức",
          en: "Decision permitting establishment of Viet Duc Vocational School of Technology",
          ja: "越独技術中級学校の設立認可決定",
          ko: "베트남·독일 기술중급학교 설립 허가 결정",
          "zh-TW": "核准設立越德科技中級學校之決定",
        },
        number: "2567/QĐ-UBND",
        date: "2026-06-26",
        issuer: {
          vi: "UBND tỉnh Quảng Trị",
          en: "Quang Tri Provincial People's Committee",
          ja: "クアンチ省人民委員会",
          ko: "꽝찌성 인민위원회",
          "zh-TW": "廣治省人民委員會",
        },
      },
    ],
    stats: [
      {
        value: "10+",
        label: {
          vi: "ngành nghề đào tạo",
          en: "training majors",
          de: "Ausbildungsrichtungen",
          ja: "の教育課程",
          ko: "개 교육 과정",
          "zh-TW": "個培訓課程",
        },
      },
      {
        value: "200+",
        label: {
          vi: "doanh nghiệp đối tác",
          en: "partner enterprises",
          de: "Partnerunternehmen",
          ja: "の提携企業",
          ko: "개 협력 기업",
          "zh-TW": "家合作企業",
        },
      },
    ],
    provenance: fromProfileVi(8),
    editorNote:
      "QUAN TRỌNG: Điều 2 khoản 4 của QĐ 2567/QĐ-UBND ghi rõ 'Trường chỉ được phép tuyển sinh và tổ chức đào tạo sau khi được cấp Giấy chứng nhận đăng ký hoạt động giáo dục nghề nghiệp'. Vì vậy các ngành của trường này chỉ hiển thị dưới dạng ĐỊNH HƯỚNG ĐÀO TẠO, không có mã ngành và không công bố chỉ tiêu tuyển sinh, cho tới khi trường cung cấp GCN đăng ký hoạt động GDNN. Hồ sơ in ghi 'Đồng Hới, tỉnh Quảng Trị'; quyết định ghi 'phường Đồng Thuận, tỉnh Quảng Trị'.",
  },
  {
    slug: "itw-berlin",
    order: 6,
    name: {
      vi: "Viện Đào tạo và Giáo dục ITW Berlin",
      en: "ITW Berlin Institute of Training and Education",
      de: "itw – Institut für Aus- und Weiterbildung gGmbH",
      ja: "ITW ベルリン教育訓練研究所",
      ko: "ITW 베를린 교육훈련원",
      "zh-TW": "ITW 柏林教育訓練學院",
    },
    shortName: {
      vi: "ITW Berlin",
      en: "ITW Berlin",
      de: "itw Berlin",
      ja: "ITW ベルリン",
      ko: "ITW 베를린",
      "zh-TW": "ITW 柏林",
    },
    tagline: {
      vi: "Chuẩn Đức – Bằng cấp có giá trị tại Đức và EU",
      en: "German standards – qualifications valued in Germany and the EU",
      de: "Deutscher Standard – Abschlüsse mit Geltung in Deutschland und der EU",
      ja: "ドイツ基準 — ドイツと EU で通用する資格",
      ko: "독일 기준 — 독일과 EU에서 인정받는 자격",
      "zh-TW": "德國標準 — 在德國與歐盟通用的資格",
    },
    summary: {
      vi: "Học viện ITW Berlin là tổ chức giáo dục tại Đức, chuyển giao chương trình đào tạo, các mã ngành và triển khai hệ thống đào tạo chuẩn quốc tế tại Việt Nam. ITW Berlin không chỉ phát triển tại Đức mà còn trực tiếp chuyển giao mô hình đào tạo, chuẩn hoá bằng cấp từ Việt Nam theo tiêu chuẩn quốc tế, giúp học sinh – sinh viên được trang bị đầy đủ kiến thức, kỹ năng và ngoại ngữ để sẵn sàng gia nhập thị trường lao động Đức và toàn cầu.",
      en: "ITW Berlin is an educational institution in Germany specialising in training programmes and vocational codes, and in building a world-class standard education system in Vietnam. ITW Berlin not only develops programmes in Germany but also transfers modern education models directly, accrediting them to Vietnamese standards so that students gain the knowledge, skills and languages needed for the German and global labour market.",
      de: "Das itw Berlin ist eine deutsche Bildungseinrichtung, die Ausbildungsprogramme und Berufsprofile überträgt und ein Bildungssystem nach internationalem Standard in Vietnam aufbaut. Neben der Arbeit in Deutschland überträgt das itw moderne Ausbildungsmodelle direkt und richtet sie an vietnamesischen Standards aus, damit Lernende Wissen, Fertigkeiten und Sprachkenntnisse für den deutschen und globalen Arbeitsmarkt erwerben.",
      ja: "ITW ベルリンはドイツの教育機関で、教育課程と職種コードを移転し、国際水準の教育体系をベトナムで展開しています。ドイツ国内での事業にとどまらず、教育モデルをそのまま移し、ベトナムで得た資格を国際基準に沿って標準化することで、学生がドイツおよび世界の労働市場に必要な知識・技能・語学を備えられるようにしています。",
      ko: "ITW 베를린은 독일의 교육 기관으로, 교육 과정과 직종 코드를 이전하고 국제 수준의 교육 체계를 베트남에서 운영합니다. 독일 안에서만 머물지 않고 교육 모형을 그대로 옮기며, 베트남에서 취득한 자격을 국제 기준에 맞추어 표준화함으로써 학생들이 독일과 세계 노동시장에 필요한 지식·기능·어학을 갖추도록 돕습니다.",
      "zh-TW":
        "ITW 柏林是德國的教育機構，負責移轉課程與職類代碼，並在越南推行符合國際標準的培訓體系。ITW 柏林不僅在德國發展，更直接移轉教學模式，使在越南取得的資格依國際標準加以認證，協助學生具備進入德國與全球勞動市場所需的知識、技能與語言能力。",
    },
    legalNameEn: "itw – Institut für Aus- und Weiterbildung gGmbH",
    city: {
      vi: "Berlin, CHLB Đức",
      en: "Berlin, Germany",
      de: "Berlin, Deutschland",
      ja: "ドイツ連邦共和国ベルリン",
      ko: "독일 연방공화국 베를린",
      "zh-TW": "德意志聯邦共和國柏林",
    },
    country: "DE",
    address: "Herzbergstraße 56–59, 10365 Berlin · Seestraße 64, 13347 Berlin",
    website: "https://itw-berlin.de/vi",
    email: "nguyenphan@itw-berlin.de",
    phone: "(030) 456 01 320",
    coverPath: "/media/schools/itw-berlin.webp",
    logoPath: "/media/schools/logos/itw-berlin.webp",
    highlights: {
      vi: [
        "Liên kết đào tạo theo tiêu chuẩn Quốc tế tại Đức",
        "Đào tạo ngôn ngữ Đức, kỹ năng chuyên môn và nghề nghiệp",
        "Cơ hội học tập, thực tập và làm việc tại CHLB Đức và Châu Âu",
        "Mở rộng tương lai toàn cầu cho người học",
      ],
      en: [
        "Educational partnerships based on German standards",
        "German language training, professional skills and vocational education",
        "Opportunities to study, practise and work in Germany and across Europe",
        "Expanding international learning opportunities for students",
      ],
      de: [
        "Bildungspartnerschaften nach deutschen Standards",
        "Deutschunterricht, Fachkompetenz und berufliche Bildung",
        "Möglichkeiten für Studium, Praktikum und Arbeit in Deutschland und Europa",
        "Erweiterte internationale Lernwege für Studierende",
      ],
    },
    stats: [
      {
        value: "1967",
        label: {
          vi: "năm thành lập tại Berlin",
          en: "founded in Berlin",
          de: "gegründet in Berlin",
          ja: "年にベルリンで設立",
          ko: "년 베를린에서 설립",
          "zh-TW": "年於柏林創立",
        },
      },
      {
        value: "50+",
        label: {
          vi: "năm hoạt động trong lĩnh vực giáo dục",
          en: "years in vocational education and training",
          de: "Jahre in der beruflichen Bildung",
          ja: "年にわたる教育分野での歩み",
          ko: "년간 교육 분야에서 활동",
          "zh-TW": "年深耕教育領域",
        },
      },
      {
        value: "2006",
        label: {
          vi: "chuyển đổi thành công ty phi lợi nhuận (gGmbH)",
          en: "converted to a non-profit gGmbH",
          de: "Umwandlung in eine gGmbH",
          ja: "非営利法人(gGmbH)へ移行",
          ko: "비영리 법인(gGmbH)으로 전환",
          "zh-TW": "轉型為非營利公司（gGmbH）",
        },
      },
    ],
    provenance: fromProfileVi(21),
    editorNote:
      "Bản tiếng Việt (tr.21) ghi ITW được thành lập năm 1967 với tên Viện Giáo dục Kỹ thuật Liên tục Berlin, theo sáng kiến của cộng đồng doanh nghiệp Berlin và các hiệp hội. Bản tiếng Anh cùng hồ sơ lại ghi do 'Vietnam Education & Technology Association in Berlin' thành lập. Hai bản mâu thuẫn – đã dùng bản tiếng Việt, cần ITW Berlin xác nhận trước khi dịch sang tiếng Đức cho thị trường Đức.",
  },
];
