/*
 * Ảnh lấy từ kho tiếp nhận. SINH TỰ ĐỘNG bằng `npm run media:kho` — sửa tay
 * ở đây sẽ bị ghi đè. Muốn thêm ảnh thì bỏ file vào kho rồi chạy lại lệnh đó.
 */
export const KHO_MEDIA: Record<string, readonly string[]> = {
  "activities": [
    "/media/activities/hd-01.webp",
    "/media/activities/hd-02.webp",
    "/media/activities/hd-03.webp",
    "/media/activities/hd-04.webp",
    "/media/activities/hd-05.webp",
    "/media/activities/hd-06.webp",
    "/media/activities/hd-07.webp",
    "/media/activities/hd-08.webp",
    "/media/activities/hd-09.webp",
    "/media/activities/hd-10.webp",
    "/media/activities/hd-11.webp",
    "/media/activities/hd-12.webp",
    "/media/activities/hd-13.webp",
    "/media/activities/hd-14.webp",
    "/media/activities/hd-15.webp",
    "/media/activities/hd-16.webp",
    "/media/activities/hd-17.webp",
    "/media/activities/hd-18.webp",
    "/media/activities/hd-19.webp",
    "/media/activities/hd-20.webp",
    "/media/activities/hd-21.webp",
    "/media/activities/hd-22.webp",
    "/media/activities/hd-23.webp",
    "/media/activities/hd-24.webp",
    "/media/activities/hd-25.webp",
    "/media/activities/hd-26.webp",
    "/media/activities/hd-27.webp",
    "/media/activities/hd-28.webp",
    "/media/activities/hd-29.webp",
    "/media/activities/hd-30.webp",
  ],
  "brand": [
    "/media/brand/vdg-01.webp",
    "/media/brand/vdg-02.webp",
  ],
  "education": [
    "/media/education/nghe-01.webp",
    "/media/education/nghe-02.webp",
    "/media/education/nghe-03.webp",
    "/media/education/nghe-04.webp",
    "/media/education/nghe-05.webp",
    "/media/education/nghe-06.webp",
    "/media/education/nghe-07.webp",
    "/media/education/nghe-08.webp",
    "/media/education/nghe-09.webp",
    "/media/education/nghe-10.webp",
    "/media/education/nghe-11.webp",
    "/media/education/nghe-12.webp",
  ],
  "investment": [
    "/media/investment/dautu-01.webp",
    "/media/investment/dautu-02.webp",
    "/media/investment/dautu-03.webp",
    "/media/investment/dautu-04.webp",
    "/media/investment/dautu-05.webp",
    "/media/investment/dautu-06.webp",
    "/media/investment/dautu-07.webp",
    "/media/investment/dautu-08.webp",
    "/media/investment/dautu-09.webp",
    "/media/investment/dautu-10.webp",
    "/media/investment/dautu-11.webp",
  ],
  "partners": [
    "/media/partners/doitac-01.webp",
    "/media/partners/doitac-02.webp",
    "/media/partners/doitac-03.webp",
    "/media/partners/doitac-04.webp",
    "/media/partners/doitac-05.webp",
    "/media/partners/doitac-06.webp",
    "/media/partners/doitac-07.webp",
    "/media/partners/doitac-08.webp",
    "/media/partners/doitac-09.webp",
    "/media/partners/doitac-10.webp",
    "/media/partners/doitac-11.webp",
    "/media/partners/doitac-12.webp",
    "/media/partners/doitac-13.webp",
    "/media/partners/doitac-14.webp",
    "/media/partners/doitac-15.webp",
    "/media/partners/doitac-16.webp",
    "/media/partners/doitac-17.webp",
    "/media/partners/doitac-18.webp",
    "/media/partners/doitac-19.webp",
    "/media/partners/doitac-20.webp",
    "/media/partners/doitac-21.webp",
    "/media/partners/doitac-22.webp",
    "/media/partners/doitac-23.webp",
    "/media/partners/doitac-24.webp",
  ],
  "schools/itw-berlin": [
    "/media/schools/itw-berlin/itw-berlin-01.webp",
    "/media/schools/itw-berlin/itw-berlin-02.webp",
    "/media/schools/itw-berlin/itw-berlin-03.webp",
    "/media/schools/itw-berlin/itw-berlin-04.webp",
    "/media/schools/itw-berlin/itw-berlin-05.webp",
    "/media/schools/itw-berlin/itw-berlin-06.webp",
  ],
  "schools/trung-cap-nghe-quoc-te-ivs": [
    "/media/schools/trung-cap-nghe-quoc-te-ivs/trung-cap-nghe-quoc-te-ivs-01.webp",
    "/media/schools/trung-cap-nghe-quoc-te-ivs/trung-cap-nghe-quoc-te-ivs-02.webp",
    "/media/schools/trung-cap-nghe-quoc-te-ivs/trung-cap-nghe-quoc-te-ivs-03.webp",
    "/media/schools/trung-cap-nghe-quoc-te-ivs/trung-cap-nghe-quoc-te-ivs-04.webp",
    "/media/schools/trung-cap-nghe-quoc-te-ivs/trung-cap-nghe-quoc-te-ivs-05.webp",
    "/media/schools/trung-cap-nghe-quoc-te-ivs/trung-cap-nghe-quoc-te-ivs-06.webp",
    "/media/schools/trung-cap-nghe-quoc-te-ivs/trung-cap-nghe-quoc-te-ivs-07.webp",
    "/media/schools/trung-cap-nghe-quoc-te-ivs/trung-cap-nghe-quoc-te-ivs-08.webp",
    "/media/schools/trung-cap-nghe-quoc-te-ivs/trung-cap-nghe-quoc-te-ivs-09.webp",
    "/media/schools/trung-cap-nghe-quoc-te-ivs/trung-cap-nghe-quoc-te-ivs-10.webp",
    "/media/schools/trung-cap-nghe-quoc-te-ivs/trung-cap-nghe-quoc-te-ivs-11.webp",
    "/media/schools/trung-cap-nghe-quoc-te-ivs/trung-cap-nghe-quoc-te-ivs-12.webp",
    "/media/schools/trung-cap-nghe-quoc-te-ivs/trung-cap-nghe-quoc-te-ivs-13.webp",
  ],
};

/** Ảnh của một nhóm, mảng rỗng nếu nhóm đó chưa có ảnh nào. */
export function khoAnh(key: string): readonly string[] {
  return KHO_MEDIA[key] ?? [];
}
